### ISSUE TITLE
Add missing dev dependency react-addons-shallow-compare

### ISSUE THREAD

**Issue by pastuxso** [camilo9020/air-quality-app#1]
```
$ npm t

> air-quality-app@0.1.0 test /Users/kommitter/Code/camilo9020/air-quality-app
> jest

 FAIL  src/__tests__/App-test.js
  ● Test suite failed to run

    Cannot find module 'react-addons-shallow-compare' from 'input.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:142:17)
      at Object.<anonymous> (node_modules/react-geosuggest/module/input.js:15:34)
      at Object.<anonymous> (node_modules/react-geosuggest/module/Geosuggest.js:35:14)

Test Summary
 › Ran all tests.
 › 1 test suite failed, 0 tests passed (0 total in 1 test suite, run time 2.07s)
npm ERR! Test failed.  See above for more details.
```

**Comment by camilo9020** [comment]
In my repository this is ok

**Comment by pastuxso** [comment]
I think that you installed the dependency without --save, please check your package.json
